fix: prevent TS2552/TS2551/TS2339 errors
app/custom-app-delegate.ts:18:13 - error TS2552: Cannot find name 'LocalNotification'. Did you mean 'UILocalNotification'?
app/custom-app-delegate.ts:30:55 - error TS2551: Property 'newData' does not exist on type 'typeof UIBackgroundFetchResult'. Did you mean 'NewData'?
app/app-delegate.ts:18:32 - error TS2339: Property 'schedule' does not exist on type 'typeof import("/Users/qkdreyer/Sites/nativescript-bluetooth-demo/Bluetooth/node_modules/nativescr...'.